name: Hello World Develop Branch
on:
  push:
    branches:
      - Develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World Action
        run: echo "Hello world from Develop branch"
